// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

/**
 * Protobuf type {@code submit_booking.BasicInfo}
 */
public  final class BasicInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:submit_booking.BasicInfo)
    BasicInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BasicInfo.newBuilder() to construct.
  private BasicInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BasicInfo() {
    currency_ = "";
    deepLink_ = "";
    locale_ = "";
    proposition_ = 0;
    websiteId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BasicInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            currency_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            deepLink_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            locale_ = s;
            break;
          }
          case 34: {
            schema.PointOfSale.Builder subBuilder = null;
            if (pointOfSale_ != null) {
              subBuilder = pointOfSale_.toBuilder();
            }
            pointOfSale_ = input.readMessage(schema.PointOfSale.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pointOfSale_);
              pointOfSale_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            proposition_ = rawValue;
            break;
          }
          case 48: {

            testBooking_ = input.readBool();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            websiteId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return schema.SubmitBooking.internal_static_submit_booking_BasicInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return schema.SubmitBooking.internal_static_submit_booking_BasicInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            schema.BasicInfo.class, schema.BasicInfo.Builder.class);
  }

  /**
   * Protobuf enum {@code submit_booking.BasicInfo.Proposition}
   */
  public enum Proposition
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Identify the the source of the request.
     * </pre>
     *
     * <code>PROPOSITION_BWS = 0;</code>
     */
    PROPOSITION_BWS(0),
    /**
     * <code>PROPOSITION_DBOOK = 1;</code>
     */
    PROPOSITION_DBOOK(1),
    /**
     * <code>PROPOSITION_UNSET = 2;</code>
     */
    PROPOSITION_UNSET(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Identify the the source of the request.
     * </pre>
     *
     * <code>PROPOSITION_BWS = 0;</code>
     */
    public static final int PROPOSITION_BWS_VALUE = 0;
    /**
     * <code>PROPOSITION_DBOOK = 1;</code>
     */
    public static final int PROPOSITION_DBOOK_VALUE = 1;
    /**
     * <code>PROPOSITION_UNSET = 2;</code>
     */
    public static final int PROPOSITION_UNSET_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Proposition valueOf(int value) {
      return forNumber(value);
    }

    public static Proposition forNumber(int value) {
      switch (value) {
        case 0: return PROPOSITION_BWS;
        case 1: return PROPOSITION_DBOOK;
        case 2: return PROPOSITION_UNSET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Proposition>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Proposition> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Proposition>() {
            public Proposition findValueByNumber(int number) {
              return Proposition.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return schema.BasicInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final Proposition[] VALUES = values();

    public static Proposition valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Proposition(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:submit_booking.BasicInfo.Proposition)
  }

  public static final int CURRENCY_FIELD_NUMBER = 1;
  private volatile java.lang.Object currency_;
  /**
   * <pre>
   * e.g.EUR
   * </pre>
   *
   * <code>string currency = 1;</code>
   */
  public java.lang.String getCurrency() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currency_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g.EUR
   * </pre>
   *
   * <code>string currency = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCurrencyBytes() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEEP_LINK_FIELD_NUMBER = 2;
  private volatile java.lang.Object deepLink_;
  /**
   * <pre>
   * the URL of deeplink
   * </pre>
   *
   * <code>string deep_link = 2;</code>
   */
  public java.lang.String getDeepLink() {
    java.lang.Object ref = deepLink_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deepLink_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the URL of deeplink
   * </pre>
   *
   * <code>string deep_link = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDeepLinkBytes() {
    java.lang.Object ref = deepLink_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deepLink_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCALE_FIELD_NUMBER = 3;
  private volatile java.lang.Object locale_;
  /**
   * <pre>
   * e.g.en-GB, pattern value="^[a-z]{2}-[a-zA-Z]{2}$"
   * </pre>
   *
   * <code>string locale = 3;</code>
   */
  public java.lang.String getLocale() {
    java.lang.Object ref = locale_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      locale_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g.en-GB, pattern value="^[a-z]{2}-[a-zA-Z]{2}$"
   * </pre>
   *
   * <code>string locale = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLocaleBytes() {
    java.lang.Object ref = locale_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      locale_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POINT_OF_SALE_FIELD_NUMBER = 4;
  private schema.PointOfSale pointOfSale_;
  /**
   * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
   */
  public boolean hasPointOfSale() {
    return pointOfSale_ != null;
  }
  /**
   * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
   */
  public schema.PointOfSale getPointOfSale() {
    return pointOfSale_ == null ? schema.PointOfSale.getDefaultInstance() : pointOfSale_;
  }
  /**
   * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
   */
  public schema.PointOfSaleOrBuilder getPointOfSaleOrBuilder() {
    return getPointOfSale();
  }

  public static final int PROPOSITION_FIELD_NUMBER = 5;
  private int proposition_;
  /**
   * <code>.submit_booking.BasicInfo.Proposition proposition = 5;</code>
   */
  public int getPropositionValue() {
    return proposition_;
  }
  /**
   * <code>.submit_booking.BasicInfo.Proposition proposition = 5;</code>
   */
  public schema.BasicInfo.Proposition getProposition() {
    @SuppressWarnings("deprecation")
    schema.BasicInfo.Proposition result = schema.BasicInfo.Proposition.valueOf(proposition_);
    return result == null ? schema.BasicInfo.Proposition.UNRECOGNIZED : result;
  }

  public static final int TEST_BOOKING_FIELD_NUMBER = 6;
  private boolean testBooking_;
  /**
   * <code>bool test_booking = 6;</code>
   */
  public boolean getTestBooking() {
    return testBooking_;
  }

  public static final int WEBSITE_ID_FIELD_NUMBER = 7;
  private volatile java.lang.Object websiteId_;
  /**
   * <pre>
   * Skyscanner website ID. e.g. byoj
   * </pre>
   *
   * <code>string website_id = 7;</code>
   */
  public java.lang.String getWebsiteId() {
    java.lang.Object ref = websiteId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      websiteId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Skyscanner website ID. e.g. byoj
   * </pre>
   *
   * <code>string website_id = 7;</code>
   */
  public com.google.protobuf.ByteString
      getWebsiteIdBytes() {
    java.lang.Object ref = websiteId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      websiteId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCurrencyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currency_);
    }
    if (!getDeepLinkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deepLink_);
    }
    if (!getLocaleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, locale_);
    }
    if (pointOfSale_ != null) {
      output.writeMessage(4, getPointOfSale());
    }
    if (proposition_ != schema.BasicInfo.Proposition.PROPOSITION_BWS.getNumber()) {
      output.writeEnum(5, proposition_);
    }
    if (testBooking_ != false) {
      output.writeBool(6, testBooking_);
    }
    if (!getWebsiteIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, websiteId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCurrencyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currency_);
    }
    if (!getDeepLinkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deepLink_);
    }
    if (!getLocaleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, locale_);
    }
    if (pointOfSale_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getPointOfSale());
    }
    if (proposition_ != schema.BasicInfo.Proposition.PROPOSITION_BWS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, proposition_);
    }
    if (testBooking_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, testBooking_);
    }
    if (!getWebsiteIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, websiteId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof schema.BasicInfo)) {
      return super.equals(obj);
    }
    schema.BasicInfo other = (schema.BasicInfo) obj;

    if (!getCurrency()
        .equals(other.getCurrency())) return false;
    if (!getDeepLink()
        .equals(other.getDeepLink())) return false;
    if (!getLocale()
        .equals(other.getLocale())) return false;
    if (hasPointOfSale() != other.hasPointOfSale()) return false;
    if (hasPointOfSale()) {
      if (!getPointOfSale()
          .equals(other.getPointOfSale())) return false;
    }
    if (proposition_ != other.proposition_) return false;
    if (getTestBooking()
        != other.getTestBooking()) return false;
    if (!getWebsiteId()
        .equals(other.getWebsiteId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getCurrency().hashCode();
    hash = (37 * hash) + DEEP_LINK_FIELD_NUMBER;
    hash = (53 * hash) + getDeepLink().hashCode();
    hash = (37 * hash) + LOCALE_FIELD_NUMBER;
    hash = (53 * hash) + getLocale().hashCode();
    if (hasPointOfSale()) {
      hash = (37 * hash) + POINT_OF_SALE_FIELD_NUMBER;
      hash = (53 * hash) + getPointOfSale().hashCode();
    }
    hash = (37 * hash) + PROPOSITION_FIELD_NUMBER;
    hash = (53 * hash) + proposition_;
    hash = (37 * hash) + TEST_BOOKING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTestBooking());
    hash = (37 * hash) + WEBSITE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWebsiteId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static schema.BasicInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.BasicInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.BasicInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.BasicInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.BasicInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.BasicInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.BasicInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static schema.BasicInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static schema.BasicInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static schema.BasicInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static schema.BasicInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static schema.BasicInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(schema.BasicInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code submit_booking.BasicInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:submit_booking.BasicInfo)
      schema.BasicInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return schema.SubmitBooking.internal_static_submit_booking_BasicInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return schema.SubmitBooking.internal_static_submit_booking_BasicInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              schema.BasicInfo.class, schema.BasicInfo.Builder.class);
    }

    // Construct using schema.BasicInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currency_ = "";

      deepLink_ = "";

      locale_ = "";

      if (pointOfSaleBuilder_ == null) {
        pointOfSale_ = null;
      } else {
        pointOfSale_ = null;
        pointOfSaleBuilder_ = null;
      }
      proposition_ = 0;

      testBooking_ = false;

      websiteId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return schema.SubmitBooking.internal_static_submit_booking_BasicInfo_descriptor;
    }

    @java.lang.Override
    public schema.BasicInfo getDefaultInstanceForType() {
      return schema.BasicInfo.getDefaultInstance();
    }

    @java.lang.Override
    public schema.BasicInfo build() {
      schema.BasicInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public schema.BasicInfo buildPartial() {
      schema.BasicInfo result = new schema.BasicInfo(this);
      result.currency_ = currency_;
      result.deepLink_ = deepLink_;
      result.locale_ = locale_;
      if (pointOfSaleBuilder_ == null) {
        result.pointOfSale_ = pointOfSale_;
      } else {
        result.pointOfSale_ = pointOfSaleBuilder_.build();
      }
      result.proposition_ = proposition_;
      result.testBooking_ = testBooking_;
      result.websiteId_ = websiteId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof schema.BasicInfo) {
        return mergeFrom((schema.BasicInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(schema.BasicInfo other) {
      if (other == schema.BasicInfo.getDefaultInstance()) return this;
      if (!other.getCurrency().isEmpty()) {
        currency_ = other.currency_;
        onChanged();
      }
      if (!other.getDeepLink().isEmpty()) {
        deepLink_ = other.deepLink_;
        onChanged();
      }
      if (!other.getLocale().isEmpty()) {
        locale_ = other.locale_;
        onChanged();
      }
      if (other.hasPointOfSale()) {
        mergePointOfSale(other.getPointOfSale());
      }
      if (other.proposition_ != 0) {
        setPropositionValue(other.getPropositionValue());
      }
      if (other.getTestBooking() != false) {
        setTestBooking(other.getTestBooking());
      }
      if (!other.getWebsiteId().isEmpty()) {
        websiteId_ = other.websiteId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      schema.BasicInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (schema.BasicInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object currency_ = "";
    /**
     * <pre>
     * e.g.EUR
     * </pre>
     *
     * <code>string currency = 1;</code>
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g.EUR
     * </pre>
     *
     * <code>string currency = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g.EUR
     * </pre>
     *
     * <code>string currency = 1;</code>
     */
    public Builder setCurrency(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currency_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g.EUR
     * </pre>
     *
     * <code>string currency = 1;</code>
     */
    public Builder clearCurrency() {
      
      currency_ = getDefaultInstance().getCurrency();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g.EUR
     * </pre>
     *
     * <code>string currency = 1;</code>
     */
    public Builder setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currency_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deepLink_ = "";
    /**
     * <pre>
     * the URL of deeplink
     * </pre>
     *
     * <code>string deep_link = 2;</code>
     */
    public java.lang.String getDeepLink() {
      java.lang.Object ref = deepLink_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deepLink_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the URL of deeplink
     * </pre>
     *
     * <code>string deep_link = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeepLinkBytes() {
      java.lang.Object ref = deepLink_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deepLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the URL of deeplink
     * </pre>
     *
     * <code>string deep_link = 2;</code>
     */
    public Builder setDeepLink(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deepLink_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the URL of deeplink
     * </pre>
     *
     * <code>string deep_link = 2;</code>
     */
    public Builder clearDeepLink() {
      
      deepLink_ = getDefaultInstance().getDeepLink();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the URL of deeplink
     * </pre>
     *
     * <code>string deep_link = 2;</code>
     */
    public Builder setDeepLinkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deepLink_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object locale_ = "";
    /**
     * <pre>
     * e.g.en-GB, pattern value="^[a-z]{2}-[a-zA-Z]{2}$"
     * </pre>
     *
     * <code>string locale = 3;</code>
     */
    public java.lang.String getLocale() {
      java.lang.Object ref = locale_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locale_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g.en-GB, pattern value="^[a-z]{2}-[a-zA-Z]{2}$"
     * </pre>
     *
     * <code>string locale = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLocaleBytes() {
      java.lang.Object ref = locale_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g.en-GB, pattern value="^[a-z]{2}-[a-zA-Z]{2}$"
     * </pre>
     *
     * <code>string locale = 3;</code>
     */
    public Builder setLocale(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      locale_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g.en-GB, pattern value="^[a-z]{2}-[a-zA-Z]{2}$"
     * </pre>
     *
     * <code>string locale = 3;</code>
     */
    public Builder clearLocale() {
      
      locale_ = getDefaultInstance().getLocale();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g.en-GB, pattern value="^[a-z]{2}-[a-zA-Z]{2}$"
     * </pre>
     *
     * <code>string locale = 3;</code>
     */
    public Builder setLocaleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      locale_ = value;
      onChanged();
      return this;
    }

    private schema.PointOfSale pointOfSale_;
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.PointOfSale, schema.PointOfSale.Builder, schema.PointOfSaleOrBuilder> pointOfSaleBuilder_;
    /**
     * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
     */
    public boolean hasPointOfSale() {
      return pointOfSaleBuilder_ != null || pointOfSale_ != null;
    }
    /**
     * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
     */
    public schema.PointOfSale getPointOfSale() {
      if (pointOfSaleBuilder_ == null) {
        return pointOfSale_ == null ? schema.PointOfSale.getDefaultInstance() : pointOfSale_;
      } else {
        return pointOfSaleBuilder_.getMessage();
      }
    }
    /**
     * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
     */
    public Builder setPointOfSale(schema.PointOfSale value) {
      if (pointOfSaleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pointOfSale_ = value;
        onChanged();
      } else {
        pointOfSaleBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
     */
    public Builder setPointOfSale(
        schema.PointOfSale.Builder builderForValue) {
      if (pointOfSaleBuilder_ == null) {
        pointOfSale_ = builderForValue.build();
        onChanged();
      } else {
        pointOfSaleBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
     */
    public Builder mergePointOfSale(schema.PointOfSale value) {
      if (pointOfSaleBuilder_ == null) {
        if (pointOfSale_ != null) {
          pointOfSale_ =
            schema.PointOfSale.newBuilder(pointOfSale_).mergeFrom(value).buildPartial();
        } else {
          pointOfSale_ = value;
        }
        onChanged();
      } else {
        pointOfSaleBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
     */
    public Builder clearPointOfSale() {
      if (pointOfSaleBuilder_ == null) {
        pointOfSale_ = null;
        onChanged();
      } else {
        pointOfSale_ = null;
        pointOfSaleBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
     */
    public schema.PointOfSale.Builder getPointOfSaleBuilder() {
      
      onChanged();
      return getPointOfSaleFieldBuilder().getBuilder();
    }
    /**
     * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
     */
    public schema.PointOfSaleOrBuilder getPointOfSaleOrBuilder() {
      if (pointOfSaleBuilder_ != null) {
        return pointOfSaleBuilder_.getMessageOrBuilder();
      } else {
        return pointOfSale_ == null ?
            schema.PointOfSale.getDefaultInstance() : pointOfSale_;
      }
    }
    /**
     * <code>.submit_booking.PointOfSale point_of_sale = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.PointOfSale, schema.PointOfSale.Builder, schema.PointOfSaleOrBuilder> 
        getPointOfSaleFieldBuilder() {
      if (pointOfSaleBuilder_ == null) {
        pointOfSaleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            schema.PointOfSale, schema.PointOfSale.Builder, schema.PointOfSaleOrBuilder>(
                getPointOfSale(),
                getParentForChildren(),
                isClean());
        pointOfSale_ = null;
      }
      return pointOfSaleBuilder_;
    }

    private int proposition_ = 0;
    /**
     * <code>.submit_booking.BasicInfo.Proposition proposition = 5;</code>
     */
    public int getPropositionValue() {
      return proposition_;
    }
    /**
     * <code>.submit_booking.BasicInfo.Proposition proposition = 5;</code>
     */
    public Builder setPropositionValue(int value) {
      proposition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.submit_booking.BasicInfo.Proposition proposition = 5;</code>
     */
    public schema.BasicInfo.Proposition getProposition() {
      @SuppressWarnings("deprecation")
      schema.BasicInfo.Proposition result = schema.BasicInfo.Proposition.valueOf(proposition_);
      return result == null ? schema.BasicInfo.Proposition.UNRECOGNIZED : result;
    }
    /**
     * <code>.submit_booking.BasicInfo.Proposition proposition = 5;</code>
     */
    public Builder setProposition(schema.BasicInfo.Proposition value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      proposition_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.submit_booking.BasicInfo.Proposition proposition = 5;</code>
     */
    public Builder clearProposition() {
      
      proposition_ = 0;
      onChanged();
      return this;
    }

    private boolean testBooking_ ;
    /**
     * <code>bool test_booking = 6;</code>
     */
    public boolean getTestBooking() {
      return testBooking_;
    }
    /**
     * <code>bool test_booking = 6;</code>
     */
    public Builder setTestBooking(boolean value) {
      
      testBooking_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool test_booking = 6;</code>
     */
    public Builder clearTestBooking() {
      
      testBooking_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object websiteId_ = "";
    /**
     * <pre>
     * Skyscanner website ID. e.g. byoj
     * </pre>
     *
     * <code>string website_id = 7;</code>
     */
    public java.lang.String getWebsiteId() {
      java.lang.Object ref = websiteId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        websiteId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Skyscanner website ID. e.g. byoj
     * </pre>
     *
     * <code>string website_id = 7;</code>
     */
    public com.google.protobuf.ByteString
        getWebsiteIdBytes() {
      java.lang.Object ref = websiteId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        websiteId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Skyscanner website ID. e.g. byoj
     * </pre>
     *
     * <code>string website_id = 7;</code>
     */
    public Builder setWebsiteId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      websiteId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Skyscanner website ID. e.g. byoj
     * </pre>
     *
     * <code>string website_id = 7;</code>
     */
    public Builder clearWebsiteId() {
      
      websiteId_ = getDefaultInstance().getWebsiteId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Skyscanner website ID. e.g. byoj
     * </pre>
     *
     * <code>string website_id = 7;</code>
     */
    public Builder setWebsiteIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      websiteId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:submit_booking.BasicInfo)
  }

  // @@protoc_insertion_point(class_scope:submit_booking.BasicInfo)
  private static final schema.BasicInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new schema.BasicInfo();
  }

  public static schema.BasicInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BasicInfo>
      PARSER = new com.google.protobuf.AbstractParser<BasicInfo>() {
    @java.lang.Override
    public BasicInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BasicInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BasicInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BasicInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public schema.BasicInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

