// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

public interface ContactInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:submit_booking.ContactInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string contact_email = 1;</code>
   */
  java.lang.String getContactEmail();
  /**
   * <code>string contact_email = 1;</code>
   */
  com.google.protobuf.ByteString
      getContactEmailBytes();

  /**
   * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
   */
  boolean hasPhoneInfo();
  /**
   * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
   */
  schema.PhoneNumber getPhoneInfo();
  /**
   * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
   */
  schema.PhoneNumberOrBuilder getPhoneInfoOrBuilder();

  /**
   * <code>.submit_booking.PostalAddress postal_address = 3;</code>
   */
  boolean hasPostalAddress();
  /**
   * <code>.submit_booking.PostalAddress postal_address = 3;</code>
   */
  schema.PostalAddress getPostalAddress();
  /**
   * <code>.submit_booking.PostalAddress postal_address = 3;</code>
   */
  schema.PostalAddressOrBuilder getPostalAddressOrBuilder();
}
