// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

/**
 * Protobuf type {@code submit_booking.ContactInfo}
 */
public  final class ContactInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:submit_booking.ContactInfo)
    ContactInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContactInfo.newBuilder() to construct.
  private ContactInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContactInfo() {
    contactEmail_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ContactInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            contactEmail_ = s;
            break;
          }
          case 18: {
            schema.PhoneNumber.Builder subBuilder = null;
            if (phoneInfo_ != null) {
              subBuilder = phoneInfo_.toBuilder();
            }
            phoneInfo_ = input.readMessage(schema.PhoneNumber.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(phoneInfo_);
              phoneInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            schema.PostalAddress.Builder subBuilder = null;
            if (postalAddress_ != null) {
              subBuilder = postalAddress_.toBuilder();
            }
            postalAddress_ = input.readMessage(schema.PostalAddress.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(postalAddress_);
              postalAddress_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return schema.SubmitBooking.internal_static_submit_booking_ContactInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return schema.SubmitBooking.internal_static_submit_booking_ContactInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            schema.ContactInfo.class, schema.ContactInfo.Builder.class);
  }

  public static final int CONTACT_EMAIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object contactEmail_;
  /**
   * <code>string contact_email = 1;</code>
   */
  public java.lang.String getContactEmail() {
    java.lang.Object ref = contactEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contactEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string contact_email = 1;</code>
   */
  public com.google.protobuf.ByteString
      getContactEmailBytes() {
    java.lang.Object ref = contactEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contactEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE_INFO_FIELD_NUMBER = 2;
  private schema.PhoneNumber phoneInfo_;
  /**
   * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
   */
  public boolean hasPhoneInfo() {
    return phoneInfo_ != null;
  }
  /**
   * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
   */
  public schema.PhoneNumber getPhoneInfo() {
    return phoneInfo_ == null ? schema.PhoneNumber.getDefaultInstance() : phoneInfo_;
  }
  /**
   * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
   */
  public schema.PhoneNumberOrBuilder getPhoneInfoOrBuilder() {
    return getPhoneInfo();
  }

  public static final int POSTAL_ADDRESS_FIELD_NUMBER = 3;
  private schema.PostalAddress postalAddress_;
  /**
   * <code>.submit_booking.PostalAddress postal_address = 3;</code>
   */
  public boolean hasPostalAddress() {
    return postalAddress_ != null;
  }
  /**
   * <code>.submit_booking.PostalAddress postal_address = 3;</code>
   */
  public schema.PostalAddress getPostalAddress() {
    return postalAddress_ == null ? schema.PostalAddress.getDefaultInstance() : postalAddress_;
  }
  /**
   * <code>.submit_booking.PostalAddress postal_address = 3;</code>
   */
  public schema.PostalAddressOrBuilder getPostalAddressOrBuilder() {
    return getPostalAddress();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getContactEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contactEmail_);
    }
    if (phoneInfo_ != null) {
      output.writeMessage(2, getPhoneInfo());
    }
    if (postalAddress_ != null) {
      output.writeMessage(3, getPostalAddress());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getContactEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contactEmail_);
    }
    if (phoneInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPhoneInfo());
    }
    if (postalAddress_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPostalAddress());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof schema.ContactInfo)) {
      return super.equals(obj);
    }
    schema.ContactInfo other = (schema.ContactInfo) obj;

    if (!getContactEmail()
        .equals(other.getContactEmail())) return false;
    if (hasPhoneInfo() != other.hasPhoneInfo()) return false;
    if (hasPhoneInfo()) {
      if (!getPhoneInfo()
          .equals(other.getPhoneInfo())) return false;
    }
    if (hasPostalAddress() != other.hasPostalAddress()) return false;
    if (hasPostalAddress()) {
      if (!getPostalAddress()
          .equals(other.getPostalAddress())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTACT_EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getContactEmail().hashCode();
    if (hasPhoneInfo()) {
      hash = (37 * hash) + PHONE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneInfo().hashCode();
    }
    if (hasPostalAddress()) {
      hash = (37 * hash) + POSTAL_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getPostalAddress().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static schema.ContactInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.ContactInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.ContactInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.ContactInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.ContactInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.ContactInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.ContactInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static schema.ContactInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static schema.ContactInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static schema.ContactInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static schema.ContactInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static schema.ContactInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(schema.ContactInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code submit_booking.ContactInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:submit_booking.ContactInfo)
      schema.ContactInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return schema.SubmitBooking.internal_static_submit_booking_ContactInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return schema.SubmitBooking.internal_static_submit_booking_ContactInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              schema.ContactInfo.class, schema.ContactInfo.Builder.class);
    }

    // Construct using schema.ContactInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      contactEmail_ = "";

      if (phoneInfoBuilder_ == null) {
        phoneInfo_ = null;
      } else {
        phoneInfo_ = null;
        phoneInfoBuilder_ = null;
      }
      if (postalAddressBuilder_ == null) {
        postalAddress_ = null;
      } else {
        postalAddress_ = null;
        postalAddressBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return schema.SubmitBooking.internal_static_submit_booking_ContactInfo_descriptor;
    }

    @java.lang.Override
    public schema.ContactInfo getDefaultInstanceForType() {
      return schema.ContactInfo.getDefaultInstance();
    }

    @java.lang.Override
    public schema.ContactInfo build() {
      schema.ContactInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public schema.ContactInfo buildPartial() {
      schema.ContactInfo result = new schema.ContactInfo(this);
      result.contactEmail_ = contactEmail_;
      if (phoneInfoBuilder_ == null) {
        result.phoneInfo_ = phoneInfo_;
      } else {
        result.phoneInfo_ = phoneInfoBuilder_.build();
      }
      if (postalAddressBuilder_ == null) {
        result.postalAddress_ = postalAddress_;
      } else {
        result.postalAddress_ = postalAddressBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof schema.ContactInfo) {
        return mergeFrom((schema.ContactInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(schema.ContactInfo other) {
      if (other == schema.ContactInfo.getDefaultInstance()) return this;
      if (!other.getContactEmail().isEmpty()) {
        contactEmail_ = other.contactEmail_;
        onChanged();
      }
      if (other.hasPhoneInfo()) {
        mergePhoneInfo(other.getPhoneInfo());
      }
      if (other.hasPostalAddress()) {
        mergePostalAddress(other.getPostalAddress());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      schema.ContactInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (schema.ContactInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object contactEmail_ = "";
    /**
     * <code>string contact_email = 1;</code>
     */
    public java.lang.String getContactEmail() {
      java.lang.Object ref = contactEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contactEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contact_email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContactEmailBytes() {
      java.lang.Object ref = contactEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contact_email = 1;</code>
     */
    public Builder setContactEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contactEmail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contact_email = 1;</code>
     */
    public Builder clearContactEmail() {
      
      contactEmail_ = getDefaultInstance().getContactEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string contact_email = 1;</code>
     */
    public Builder setContactEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contactEmail_ = value;
      onChanged();
      return this;
    }

    private schema.PhoneNumber phoneInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.PhoneNumber, schema.PhoneNumber.Builder, schema.PhoneNumberOrBuilder> phoneInfoBuilder_;
    /**
     * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
     */
    public boolean hasPhoneInfo() {
      return phoneInfoBuilder_ != null || phoneInfo_ != null;
    }
    /**
     * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
     */
    public schema.PhoneNumber getPhoneInfo() {
      if (phoneInfoBuilder_ == null) {
        return phoneInfo_ == null ? schema.PhoneNumber.getDefaultInstance() : phoneInfo_;
      } else {
        return phoneInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
     */
    public Builder setPhoneInfo(schema.PhoneNumber value) {
      if (phoneInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        phoneInfo_ = value;
        onChanged();
      } else {
        phoneInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
     */
    public Builder setPhoneInfo(
        schema.PhoneNumber.Builder builderForValue) {
      if (phoneInfoBuilder_ == null) {
        phoneInfo_ = builderForValue.build();
        onChanged();
      } else {
        phoneInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
     */
    public Builder mergePhoneInfo(schema.PhoneNumber value) {
      if (phoneInfoBuilder_ == null) {
        if (phoneInfo_ != null) {
          phoneInfo_ =
            schema.PhoneNumber.newBuilder(phoneInfo_).mergeFrom(value).buildPartial();
        } else {
          phoneInfo_ = value;
        }
        onChanged();
      } else {
        phoneInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
     */
    public Builder clearPhoneInfo() {
      if (phoneInfoBuilder_ == null) {
        phoneInfo_ = null;
        onChanged();
      } else {
        phoneInfo_ = null;
        phoneInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
     */
    public schema.PhoneNumber.Builder getPhoneInfoBuilder() {
      
      onChanged();
      return getPhoneInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
     */
    public schema.PhoneNumberOrBuilder getPhoneInfoOrBuilder() {
      if (phoneInfoBuilder_ != null) {
        return phoneInfoBuilder_.getMessageOrBuilder();
      } else {
        return phoneInfo_ == null ?
            schema.PhoneNumber.getDefaultInstance() : phoneInfo_;
      }
    }
    /**
     * <code>.submit_booking.PhoneNumber phone_info = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.PhoneNumber, schema.PhoneNumber.Builder, schema.PhoneNumberOrBuilder> 
        getPhoneInfoFieldBuilder() {
      if (phoneInfoBuilder_ == null) {
        phoneInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            schema.PhoneNumber, schema.PhoneNumber.Builder, schema.PhoneNumberOrBuilder>(
                getPhoneInfo(),
                getParentForChildren(),
                isClean());
        phoneInfo_ = null;
      }
      return phoneInfoBuilder_;
    }

    private schema.PostalAddress postalAddress_;
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.PostalAddress, schema.PostalAddress.Builder, schema.PostalAddressOrBuilder> postalAddressBuilder_;
    /**
     * <code>.submit_booking.PostalAddress postal_address = 3;</code>
     */
    public boolean hasPostalAddress() {
      return postalAddressBuilder_ != null || postalAddress_ != null;
    }
    /**
     * <code>.submit_booking.PostalAddress postal_address = 3;</code>
     */
    public schema.PostalAddress getPostalAddress() {
      if (postalAddressBuilder_ == null) {
        return postalAddress_ == null ? schema.PostalAddress.getDefaultInstance() : postalAddress_;
      } else {
        return postalAddressBuilder_.getMessage();
      }
    }
    /**
     * <code>.submit_booking.PostalAddress postal_address = 3;</code>
     */
    public Builder setPostalAddress(schema.PostalAddress value) {
      if (postalAddressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        postalAddress_ = value;
        onChanged();
      } else {
        postalAddressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.PostalAddress postal_address = 3;</code>
     */
    public Builder setPostalAddress(
        schema.PostalAddress.Builder builderForValue) {
      if (postalAddressBuilder_ == null) {
        postalAddress_ = builderForValue.build();
        onChanged();
      } else {
        postalAddressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.submit_booking.PostalAddress postal_address = 3;</code>
     */
    public Builder mergePostalAddress(schema.PostalAddress value) {
      if (postalAddressBuilder_ == null) {
        if (postalAddress_ != null) {
          postalAddress_ =
            schema.PostalAddress.newBuilder(postalAddress_).mergeFrom(value).buildPartial();
        } else {
          postalAddress_ = value;
        }
        onChanged();
      } else {
        postalAddressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.PostalAddress postal_address = 3;</code>
     */
    public Builder clearPostalAddress() {
      if (postalAddressBuilder_ == null) {
        postalAddress_ = null;
        onChanged();
      } else {
        postalAddress_ = null;
        postalAddressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.submit_booking.PostalAddress postal_address = 3;</code>
     */
    public schema.PostalAddress.Builder getPostalAddressBuilder() {
      
      onChanged();
      return getPostalAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.submit_booking.PostalAddress postal_address = 3;</code>
     */
    public schema.PostalAddressOrBuilder getPostalAddressOrBuilder() {
      if (postalAddressBuilder_ != null) {
        return postalAddressBuilder_.getMessageOrBuilder();
      } else {
        return postalAddress_ == null ?
            schema.PostalAddress.getDefaultInstance() : postalAddress_;
      }
    }
    /**
     * <code>.submit_booking.PostalAddress postal_address = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.PostalAddress, schema.PostalAddress.Builder, schema.PostalAddressOrBuilder> 
        getPostalAddressFieldBuilder() {
      if (postalAddressBuilder_ == null) {
        postalAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            schema.PostalAddress, schema.PostalAddress.Builder, schema.PostalAddressOrBuilder>(
                getPostalAddress(),
                getParentForChildren(),
                isClean());
        postalAddress_ = null;
      }
      return postalAddressBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:submit_booking.ContactInfo)
  }

  // @@protoc_insertion_point(class_scope:submit_booking.ContactInfo)
  private static final schema.ContactInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new schema.ContactInfo();
  }

  public static schema.ContactInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContactInfo>
      PARSER = new com.google.protobuf.AbstractParser<ContactInfo>() {
    @java.lang.Override
    public ContactInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ContactInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ContactInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContactInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public schema.ContactInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

