// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

public interface FlightDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:submit_booking.FlightData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .submit_booking.Leg legs = 1;</code>
   */
  java.util.List<schema.Leg> 
      getLegsList();
  /**
   * <code>repeated .submit_booking.Leg legs = 1;</code>
   */
  schema.Leg getLegs(int index);
  /**
   * <code>repeated .submit_booking.Leg legs = 1;</code>
   */
  int getLegsCount();
  /**
   * <code>repeated .submit_booking.Leg legs = 1;</code>
   */
  java.util.List<? extends schema.LegOrBuilder> 
      getLegsOrBuilderList();
  /**
   * <code>repeated .submit_booking.Leg legs = 1;</code>
   */
  schema.LegOrBuilder getLegsOrBuilder(
      int index);

  /**
   * <code>repeated .submit_booking.Segment segments = 2;</code>
   */
  java.util.List<schema.Segment> 
      getSegmentsList();
  /**
   * <code>repeated .submit_booking.Segment segments = 2;</code>
   */
  schema.Segment getSegments(int index);
  /**
   * <code>repeated .submit_booking.Segment segments = 2;</code>
   */
  int getSegmentsCount();
  /**
   * <code>repeated .submit_booking.Segment segments = 2;</code>
   */
  java.util.List<? extends schema.SegmentOrBuilder> 
      getSegmentsOrBuilderList();
  /**
   * <code>repeated .submit_booking.Segment segments = 2;</code>
   */
  schema.SegmentOrBuilder getSegmentsOrBuilder(
      int index);
}
