// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

public interface NameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:submit_booking.Name)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string first_name = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string middle_name = 3;</code>
   */
  java.lang.String getMiddleName();
  /**
   * <code>string middle_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getMiddleNameBytes();

  /**
   * <code>.submit_booking.Name.Title title = 4;</code>
   */
  int getTitleValue();
  /**
   * <code>.submit_booking.Name.Title title = 4;</code>
   */
  schema.Name.Title getTitle();
}
