// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

public interface PaymentMethodOrBuilder extends
    // @@protoc_insertion_point(interface_extends:submit_booking.PaymentMethod)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.submit_booking.PaymentCard payment_card = 1;</code>
   */
  boolean hasPaymentCard();
  /**
   * <code>.submit_booking.PaymentCard payment_card = 1;</code>
   */
  schema.PaymentCard getPaymentCard();
  /**
   * <code>.submit_booking.PaymentCard payment_card = 1;</code>
   */
  schema.PaymentCardOrBuilder getPaymentCardOrBuilder();
}
