// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

/**
 * Protobuf type {@code submit_booking.PaymentInfo}
 */
public  final class PaymentInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:submit_booking.PaymentInfo)
    PaymentInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaymentInfo.newBuilder() to construct.
  private PaymentInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaymentInfo() {
    fraudDataToken_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PaymentInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            fraudDataToken_ = s;
            break;
          }
          case 18: {
            schema.PaymentMethod.Builder subBuilder = null;
            if (paymentMethod_ != null) {
              subBuilder = paymentMethod_.toBuilder();
            }
            paymentMethod_ = input.readMessage(schema.PaymentMethod.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(paymentMethod_);
              paymentMethod_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            schema.PaymentPrice.Builder subBuilder = null;
            if (paymentPrice_ != null) {
              subBuilder = paymentPrice_.toBuilder();
            }
            paymentPrice_ = input.readMessage(schema.PaymentPrice.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(paymentPrice_);
              paymentPrice_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return schema.SubmitBooking.internal_static_submit_booking_PaymentInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return schema.SubmitBooking.internal_static_submit_booking_PaymentInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            schema.PaymentInfo.class, schema.PaymentInfo.Builder.class);
  }

  public static final int FRAUD_DATA_TOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object fraudDataToken_;
  /**
   * <code>string fraud_data_token = 1;</code>
   */
  public java.lang.String getFraudDataToken() {
    java.lang.Object ref = fraudDataToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fraudDataToken_ = s;
      return s;
    }
  }
  /**
   * <code>string fraud_data_token = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFraudDataTokenBytes() {
    java.lang.Object ref = fraudDataToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fraudDataToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYMENT_METHOD_FIELD_NUMBER = 2;
  private schema.PaymentMethod paymentMethod_;
  /**
   * <pre>
   * A form of procedure for the payment of goods or services,
   * plus any transactional information specific to the payment method other than the amount.
   * </pre>
   *
   * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
   */
  public boolean hasPaymentMethod() {
    return paymentMethod_ != null;
  }
  /**
   * <pre>
   * A form of procedure for the payment of goods or services,
   * plus any transactional information specific to the payment method other than the amount.
   * </pre>
   *
   * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
   */
  public schema.PaymentMethod getPaymentMethod() {
    return paymentMethod_ == null ? schema.PaymentMethod.getDefaultInstance() : paymentMethod_;
  }
  /**
   * <pre>
   * A form of procedure for the payment of goods or services,
   * plus any transactional information specific to the payment method other than the amount.
   * </pre>
   *
   * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
   */
  public schema.PaymentMethodOrBuilder getPaymentMethodOrBuilder() {
    return getPaymentMethod();
  }

  public static final int PAYMENT_PRICE_FIELD_NUMBER = 3;
  private schema.PaymentPrice paymentPrice_;
  /**
   * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
   */
  public boolean hasPaymentPrice() {
    return paymentPrice_ != null;
  }
  /**
   * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
   */
  public schema.PaymentPrice getPaymentPrice() {
    return paymentPrice_ == null ? schema.PaymentPrice.getDefaultInstance() : paymentPrice_;
  }
  /**
   * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
   */
  public schema.PaymentPriceOrBuilder getPaymentPriceOrBuilder() {
    return getPaymentPrice();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFraudDataTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fraudDataToken_);
    }
    if (paymentMethod_ != null) {
      output.writeMessage(2, getPaymentMethod());
    }
    if (paymentPrice_ != null) {
      output.writeMessage(3, getPaymentPrice());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFraudDataTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fraudDataToken_);
    }
    if (paymentMethod_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPaymentMethod());
    }
    if (paymentPrice_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPaymentPrice());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof schema.PaymentInfo)) {
      return super.equals(obj);
    }
    schema.PaymentInfo other = (schema.PaymentInfo) obj;

    if (!getFraudDataToken()
        .equals(other.getFraudDataToken())) return false;
    if (hasPaymentMethod() != other.hasPaymentMethod()) return false;
    if (hasPaymentMethod()) {
      if (!getPaymentMethod()
          .equals(other.getPaymentMethod())) return false;
    }
    if (hasPaymentPrice() != other.hasPaymentPrice()) return false;
    if (hasPaymentPrice()) {
      if (!getPaymentPrice()
          .equals(other.getPaymentPrice())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FRAUD_DATA_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getFraudDataToken().hashCode();
    if (hasPaymentMethod()) {
      hash = (37 * hash) + PAYMENT_METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentMethod().hashCode();
    }
    if (hasPaymentPrice()) {
      hash = (37 * hash) + PAYMENT_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentPrice().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static schema.PaymentInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.PaymentInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.PaymentInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.PaymentInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.PaymentInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.PaymentInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.PaymentInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static schema.PaymentInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static schema.PaymentInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static schema.PaymentInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static schema.PaymentInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static schema.PaymentInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(schema.PaymentInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code submit_booking.PaymentInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:submit_booking.PaymentInfo)
      schema.PaymentInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return schema.SubmitBooking.internal_static_submit_booking_PaymentInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return schema.SubmitBooking.internal_static_submit_booking_PaymentInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              schema.PaymentInfo.class, schema.PaymentInfo.Builder.class);
    }

    // Construct using schema.PaymentInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      fraudDataToken_ = "";

      if (paymentMethodBuilder_ == null) {
        paymentMethod_ = null;
      } else {
        paymentMethod_ = null;
        paymentMethodBuilder_ = null;
      }
      if (paymentPriceBuilder_ == null) {
        paymentPrice_ = null;
      } else {
        paymentPrice_ = null;
        paymentPriceBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return schema.SubmitBooking.internal_static_submit_booking_PaymentInfo_descriptor;
    }

    @java.lang.Override
    public schema.PaymentInfo getDefaultInstanceForType() {
      return schema.PaymentInfo.getDefaultInstance();
    }

    @java.lang.Override
    public schema.PaymentInfo build() {
      schema.PaymentInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public schema.PaymentInfo buildPartial() {
      schema.PaymentInfo result = new schema.PaymentInfo(this);
      result.fraudDataToken_ = fraudDataToken_;
      if (paymentMethodBuilder_ == null) {
        result.paymentMethod_ = paymentMethod_;
      } else {
        result.paymentMethod_ = paymentMethodBuilder_.build();
      }
      if (paymentPriceBuilder_ == null) {
        result.paymentPrice_ = paymentPrice_;
      } else {
        result.paymentPrice_ = paymentPriceBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof schema.PaymentInfo) {
        return mergeFrom((schema.PaymentInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(schema.PaymentInfo other) {
      if (other == schema.PaymentInfo.getDefaultInstance()) return this;
      if (!other.getFraudDataToken().isEmpty()) {
        fraudDataToken_ = other.fraudDataToken_;
        onChanged();
      }
      if (other.hasPaymentMethod()) {
        mergePaymentMethod(other.getPaymentMethod());
      }
      if (other.hasPaymentPrice()) {
        mergePaymentPrice(other.getPaymentPrice());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      schema.PaymentInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (schema.PaymentInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object fraudDataToken_ = "";
    /**
     * <code>string fraud_data_token = 1;</code>
     */
    public java.lang.String getFraudDataToken() {
      java.lang.Object ref = fraudDataToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fraudDataToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fraud_data_token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFraudDataTokenBytes() {
      java.lang.Object ref = fraudDataToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fraudDataToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fraud_data_token = 1;</code>
     */
    public Builder setFraudDataToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fraudDataToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fraud_data_token = 1;</code>
     */
    public Builder clearFraudDataToken() {
      
      fraudDataToken_ = getDefaultInstance().getFraudDataToken();
      onChanged();
      return this;
    }
    /**
     * <code>string fraud_data_token = 1;</code>
     */
    public Builder setFraudDataTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fraudDataToken_ = value;
      onChanged();
      return this;
    }

    private schema.PaymentMethod paymentMethod_;
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.PaymentMethod, schema.PaymentMethod.Builder, schema.PaymentMethodOrBuilder> paymentMethodBuilder_;
    /**
     * <pre>
     * A form of procedure for the payment of goods or services,
     * plus any transactional information specific to the payment method other than the amount.
     * </pre>
     *
     * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
     */
    public boolean hasPaymentMethod() {
      return paymentMethodBuilder_ != null || paymentMethod_ != null;
    }
    /**
     * <pre>
     * A form of procedure for the payment of goods or services,
     * plus any transactional information specific to the payment method other than the amount.
     * </pre>
     *
     * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
     */
    public schema.PaymentMethod getPaymentMethod() {
      if (paymentMethodBuilder_ == null) {
        return paymentMethod_ == null ? schema.PaymentMethod.getDefaultInstance() : paymentMethod_;
      } else {
        return paymentMethodBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * A form of procedure for the payment of goods or services,
     * plus any transactional information specific to the payment method other than the amount.
     * </pre>
     *
     * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
     */
    public Builder setPaymentMethod(schema.PaymentMethod value) {
      if (paymentMethodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        paymentMethod_ = value;
        onChanged();
      } else {
        paymentMethodBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * A form of procedure for the payment of goods or services,
     * plus any transactional information specific to the payment method other than the amount.
     * </pre>
     *
     * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
     */
    public Builder setPaymentMethod(
        schema.PaymentMethod.Builder builderForValue) {
      if (paymentMethodBuilder_ == null) {
        paymentMethod_ = builderForValue.build();
        onChanged();
      } else {
        paymentMethodBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * A form of procedure for the payment of goods or services,
     * plus any transactional information specific to the payment method other than the amount.
     * </pre>
     *
     * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
     */
    public Builder mergePaymentMethod(schema.PaymentMethod value) {
      if (paymentMethodBuilder_ == null) {
        if (paymentMethod_ != null) {
          paymentMethod_ =
            schema.PaymentMethod.newBuilder(paymentMethod_).mergeFrom(value).buildPartial();
        } else {
          paymentMethod_ = value;
        }
        onChanged();
      } else {
        paymentMethodBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * A form of procedure for the payment of goods or services,
     * plus any transactional information specific to the payment method other than the amount.
     * </pre>
     *
     * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
     */
    public Builder clearPaymentMethod() {
      if (paymentMethodBuilder_ == null) {
        paymentMethod_ = null;
        onChanged();
      } else {
        paymentMethod_ = null;
        paymentMethodBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * A form of procedure for the payment of goods or services,
     * plus any transactional information specific to the payment method other than the amount.
     * </pre>
     *
     * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
     */
    public schema.PaymentMethod.Builder getPaymentMethodBuilder() {
      
      onChanged();
      return getPaymentMethodFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * A form of procedure for the payment of goods or services,
     * plus any transactional information specific to the payment method other than the amount.
     * </pre>
     *
     * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
     */
    public schema.PaymentMethodOrBuilder getPaymentMethodOrBuilder() {
      if (paymentMethodBuilder_ != null) {
        return paymentMethodBuilder_.getMessageOrBuilder();
      } else {
        return paymentMethod_ == null ?
            schema.PaymentMethod.getDefaultInstance() : paymentMethod_;
      }
    }
    /**
     * <pre>
     * A form of procedure for the payment of goods or services,
     * plus any transactional information specific to the payment method other than the amount.
     * </pre>
     *
     * <code>.submit_booking.PaymentMethod payment_method = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.PaymentMethod, schema.PaymentMethod.Builder, schema.PaymentMethodOrBuilder> 
        getPaymentMethodFieldBuilder() {
      if (paymentMethodBuilder_ == null) {
        paymentMethodBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            schema.PaymentMethod, schema.PaymentMethod.Builder, schema.PaymentMethodOrBuilder>(
                getPaymentMethod(),
                getParentForChildren(),
                isClean());
        paymentMethod_ = null;
      }
      return paymentMethodBuilder_;
    }

    private schema.PaymentPrice paymentPrice_;
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.PaymentPrice, schema.PaymentPrice.Builder, schema.PaymentPriceOrBuilder> paymentPriceBuilder_;
    /**
     * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
     */
    public boolean hasPaymentPrice() {
      return paymentPriceBuilder_ != null || paymentPrice_ != null;
    }
    /**
     * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
     */
    public schema.PaymentPrice getPaymentPrice() {
      if (paymentPriceBuilder_ == null) {
        return paymentPrice_ == null ? schema.PaymentPrice.getDefaultInstance() : paymentPrice_;
      } else {
        return paymentPriceBuilder_.getMessage();
      }
    }
    /**
     * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
     */
    public Builder setPaymentPrice(schema.PaymentPrice value) {
      if (paymentPriceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        paymentPrice_ = value;
        onChanged();
      } else {
        paymentPriceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
     */
    public Builder setPaymentPrice(
        schema.PaymentPrice.Builder builderForValue) {
      if (paymentPriceBuilder_ == null) {
        paymentPrice_ = builderForValue.build();
        onChanged();
      } else {
        paymentPriceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
     */
    public Builder mergePaymentPrice(schema.PaymentPrice value) {
      if (paymentPriceBuilder_ == null) {
        if (paymentPrice_ != null) {
          paymentPrice_ =
            schema.PaymentPrice.newBuilder(paymentPrice_).mergeFrom(value).buildPartial();
        } else {
          paymentPrice_ = value;
        }
        onChanged();
      } else {
        paymentPriceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
     */
    public Builder clearPaymentPrice() {
      if (paymentPriceBuilder_ == null) {
        paymentPrice_ = null;
        onChanged();
      } else {
        paymentPrice_ = null;
        paymentPriceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
     */
    public schema.PaymentPrice.Builder getPaymentPriceBuilder() {
      
      onChanged();
      return getPaymentPriceFieldBuilder().getBuilder();
    }
    /**
     * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
     */
    public schema.PaymentPriceOrBuilder getPaymentPriceOrBuilder() {
      if (paymentPriceBuilder_ != null) {
        return paymentPriceBuilder_.getMessageOrBuilder();
      } else {
        return paymentPrice_ == null ?
            schema.PaymentPrice.getDefaultInstance() : paymentPrice_;
      }
    }
    /**
     * <code>.submit_booking.PaymentPrice payment_price = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.PaymentPrice, schema.PaymentPrice.Builder, schema.PaymentPriceOrBuilder> 
        getPaymentPriceFieldBuilder() {
      if (paymentPriceBuilder_ == null) {
        paymentPriceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            schema.PaymentPrice, schema.PaymentPrice.Builder, schema.PaymentPriceOrBuilder>(
                getPaymentPrice(),
                getParentForChildren(),
                isClean());
        paymentPrice_ = null;
      }
      return paymentPriceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:submit_booking.PaymentInfo)
  }

  // @@protoc_insertion_point(class_scope:submit_booking.PaymentInfo)
  private static final schema.PaymentInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new schema.PaymentInfo();
  }

  public static schema.PaymentInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaymentInfo>
      PARSER = new com.google.protobuf.AbstractParser<PaymentInfo>() {
    @java.lang.Override
    public PaymentInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PaymentInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PaymentInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaymentInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public schema.PaymentInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

