// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

public interface PaymentPriceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:submit_booking.PaymentPrice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.submit_booking.PriceBreakdown price_breakdown = 1;</code>
   */
  boolean hasPriceBreakdown();
  /**
   * <code>.submit_booking.PriceBreakdown price_breakdown = 1;</code>
   */
  schema.PriceBreakdown getPriceBreakdown();
  /**
   * <code>.submit_booking.PriceBreakdown price_breakdown = 1;</code>
   */
  schema.PriceBreakdownOrBuilder getPriceBreakdownOrBuilder();

  /**
   * <code>.submit_booking.Price total_amount = 2;</code>
   */
  boolean hasTotalAmount();
  /**
   * <code>.submit_booking.Price total_amount = 2;</code>
   */
  schema.Price getTotalAmount();
  /**
   * <code>.submit_booking.Price total_amount = 2;</code>
   */
  schema.PriceOrBuilder getTotalAmountOrBuilder();
}
