// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

public interface PaymentCardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:submit_booking.PaymentCard)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A two-letter code assigned according to IATA Resolution 728. Example: VI for Visa
   * </pre>
   *
   * <code>string card_brand_code = 1;</code>
   */
  java.lang.String getCardBrandCode();
  /**
   * <pre>
   * A two-letter code assigned according to IATA Resolution 728. Example: VI for Visa
   * </pre>
   *
   * <code>string card_brand_code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCardBrandCodeBytes();

  /**
   * <pre>
   * Used to specify whether the card is a Consumer (personal) or Commercial (corporate) card.
   * </pre>
   *
   * <code>string card_product_type_code = 2;</code>
   */
  java.lang.String getCardProductTypeCode();
  /**
   * <pre>
   * Used to specify whether the card is a Consumer (personal) or Commercial (corporate) card.
   * </pre>
   *
   * <code>string card_product_type_code = 2;</code>
   */
  com.google.protobuf.ByteString
      getCardProductTypeCodeBytes();

  /**
   * <pre>
   * Additional description for the magnetic stripe card type (debit card, credit card, prepaid card, etc.)
   * </pre>
   *
   * <code>string card_type_text = 3;</code>
   */
  java.lang.String getCardTypeText();
  /**
   * <pre>
   * Additional description for the magnetic stripe card type (debit card, credit card, prepaid card, etc.)
   * </pre>
   *
   * <code>string card_type_text = 3;</code>
   */
  com.google.protobuf.ByteString
      getCardTypeTextBytes();

  /**
   * <code>string encrypted_card_number = 4;</code>
   */
  java.lang.String getEncryptedCardNumber();
  /**
   * <code>string encrypted_card_number = 4;</code>
   */
  com.google.protobuf.ByteString
      getEncryptedCardNumberBytes();

  /**
   * <pre>
   * 3-digit number printed on the signature panel on the back of the card and following the last four digits of the
   * Primary Account Number (PAN). For American Express,  4 digits located on the front of the card, above the card
   * number on the right hand side. Visa - CVV2, MasterCard - CVC2, American Express - CID, Discover - CMID,
   * Union Pay - CVN2, JCB - CAV2.
   * It should be a nonce provided by Braintree since Skyscanner is not PCI compliance.
   * </pre>
   *
   * <code>string encrypted_card_security_code = 5;</code>
   */
  java.lang.String getEncryptedCardSecurityCode();
  /**
   * <pre>
   * 3-digit number printed on the signature panel on the back of the card and following the last four digits of the
   * Primary Account Number (PAN). For American Express,  4 digits located on the front of the card, above the card
   * number on the right hand side. Visa - CVV2, MasterCard - CVC2, American Express - CID, Discover - CMID,
   * Union Pay - CVN2, JCB - CAV2.
   * It should be a nonce provided by Braintree since Skyscanner is not PCI compliance.
   * </pre>
   *
   * <code>string encrypted_card_security_code = 5;</code>
   */
  com.google.protobuf.ByteString
      getEncryptedCardSecurityCodeBytes();

  /**
   * <pre>
   * The last month of validity Example: 0119
   * </pre>
   *
   * <code>string expiration_date = 6;</code>
   */
  java.lang.String getExpirationDate();
  /**
   * <pre>
   * The last month of validity Example: 0119
   * </pre>
   *
   * <code>string expiration_date = 6;</code>
   */
  com.google.protobuf.ByteString
      getExpirationDateBytes();

  /**
   * <code>.submit_booking.ContactInfo holder_contact = 7;</code>
   */
  boolean hasHolderContact();
  /**
   * <code>.submit_booking.ContactInfo holder_contact = 7;</code>
   */
  schema.ContactInfo getHolderContact();
  /**
   * <code>.submit_booking.ContactInfo holder_contact = 7;</code>
   */
  schema.ContactInfoOrBuilder getHolderContactOrBuilder();

  /**
   * <code>.submit_booking.Name holder_name = 8;</code>
   */
  boolean hasHolderName();
  /**
   * <code>.submit_booking.Name holder_name = 8;</code>
   */
  schema.Name getHolderName();
  /**
   * <code>.submit_booking.Name holder_name = 8;</code>
   */
  schema.NameOrBuilder getHolderNameOrBuilder();
}
