// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

/**
 * Protobuf type {@code submit_booking.PointOfSale}
 */
public  final class PointOfSale extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:submit_booking.PointOfSale)
    PointOfSaleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PointOfSale.newBuilder() to construct.
  private PointOfSale(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PointOfSale() {
    market_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PointOfSale(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            schema.DeviceInfo.Builder subBuilder = null;
            if (deviceInfo_ != null) {
              subBuilder = deviceInfo_.toBuilder();
            }
            deviceInfo_ = input.readMessage(schema.DeviceInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deviceInfo_);
              deviceInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            schema.Location.Builder subBuilder = null;
            if (location_ != null) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(schema.Location.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            market_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return schema.SubmitBooking.internal_static_submit_booking_PointOfSale_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return schema.SubmitBooking.internal_static_submit_booking_PointOfSale_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            schema.PointOfSale.class, schema.PointOfSale.Builder.class);
  }

  public static final int DEVICE_INFO_FIELD_NUMBER = 1;
  private schema.DeviceInfo deviceInfo_;
  /**
   * <code>.submit_booking.DeviceInfo device_info = 1;</code>
   */
  public boolean hasDeviceInfo() {
    return deviceInfo_ != null;
  }
  /**
   * <code>.submit_booking.DeviceInfo device_info = 1;</code>
   */
  public schema.DeviceInfo getDeviceInfo() {
    return deviceInfo_ == null ? schema.DeviceInfo.getDefaultInstance() : deviceInfo_;
  }
  /**
   * <code>.submit_booking.DeviceInfo device_info = 1;</code>
   */
  public schema.DeviceInfoOrBuilder getDeviceInfoOrBuilder() {
    return getDeviceInfo();
  }

  public static final int LOCATION_FIELD_NUMBER = 2;
  private schema.Location location_;
  /**
   * <code>.submit_booking.Location location = 2;</code>
   */
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <code>.submit_booking.Location location = 2;</code>
   */
  public schema.Location getLocation() {
    return location_ == null ? schema.Location.getDefaultInstance() : location_;
  }
  /**
   * <code>.submit_booking.Location location = 2;</code>
   */
  public schema.LocationOrBuilder getLocationOrBuilder() {
    return getLocation();
  }

  public static final int MARKET_FIELD_NUMBER = 3;
  private volatile java.lang.Object market_;
  /**
   * <pre>
   * e.g.UK,pattern value="^[A-Z]{2}$"
   * </pre>
   *
   * <code>string market = 3;</code>
   */
  public java.lang.String getMarket() {
    java.lang.Object ref = market_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      market_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g.UK,pattern value="^[A-Z]{2}$"
   * </pre>
   *
   * <code>string market = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMarketBytes() {
    java.lang.Object ref = market_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      market_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (deviceInfo_ != null) {
      output.writeMessage(1, getDeviceInfo());
    }
    if (location_ != null) {
      output.writeMessage(2, getLocation());
    }
    if (!getMarketBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, market_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (deviceInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDeviceInfo());
    }
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLocation());
    }
    if (!getMarketBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, market_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof schema.PointOfSale)) {
      return super.equals(obj);
    }
    schema.PointOfSale other = (schema.PointOfSale) obj;

    if (hasDeviceInfo() != other.hasDeviceInfo()) return false;
    if (hasDeviceInfo()) {
      if (!getDeviceInfo()
          .equals(other.getDeviceInfo())) return false;
    }
    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (!getMarket()
        .equals(other.getMarket())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDeviceInfo()) {
      hash = (37 * hash) + DEVICE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceInfo().hashCode();
    }
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    hash = (37 * hash) + MARKET_FIELD_NUMBER;
    hash = (53 * hash) + getMarket().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static schema.PointOfSale parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.PointOfSale parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.PointOfSale parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.PointOfSale parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.PointOfSale parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static schema.PointOfSale parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static schema.PointOfSale parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static schema.PointOfSale parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static schema.PointOfSale parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static schema.PointOfSale parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static schema.PointOfSale parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static schema.PointOfSale parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(schema.PointOfSale prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code submit_booking.PointOfSale}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:submit_booking.PointOfSale)
      schema.PointOfSaleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return schema.SubmitBooking.internal_static_submit_booking_PointOfSale_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return schema.SubmitBooking.internal_static_submit_booking_PointOfSale_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              schema.PointOfSale.class, schema.PointOfSale.Builder.class);
    }

    // Construct using schema.PointOfSale.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (deviceInfoBuilder_ == null) {
        deviceInfo_ = null;
      } else {
        deviceInfo_ = null;
        deviceInfoBuilder_ = null;
      }
      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        location_ = null;
        locationBuilder_ = null;
      }
      market_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return schema.SubmitBooking.internal_static_submit_booking_PointOfSale_descriptor;
    }

    @java.lang.Override
    public schema.PointOfSale getDefaultInstanceForType() {
      return schema.PointOfSale.getDefaultInstance();
    }

    @java.lang.Override
    public schema.PointOfSale build() {
      schema.PointOfSale result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public schema.PointOfSale buildPartial() {
      schema.PointOfSale result = new schema.PointOfSale(this);
      if (deviceInfoBuilder_ == null) {
        result.deviceInfo_ = deviceInfo_;
      } else {
        result.deviceInfo_ = deviceInfoBuilder_.build();
      }
      if (locationBuilder_ == null) {
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      result.market_ = market_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof schema.PointOfSale) {
        return mergeFrom((schema.PointOfSale)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(schema.PointOfSale other) {
      if (other == schema.PointOfSale.getDefaultInstance()) return this;
      if (other.hasDeviceInfo()) {
        mergeDeviceInfo(other.getDeviceInfo());
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      if (!other.getMarket().isEmpty()) {
        market_ = other.market_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      schema.PointOfSale parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (schema.PointOfSale) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private schema.DeviceInfo deviceInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.DeviceInfo, schema.DeviceInfo.Builder, schema.DeviceInfoOrBuilder> deviceInfoBuilder_;
    /**
     * <code>.submit_booking.DeviceInfo device_info = 1;</code>
     */
    public boolean hasDeviceInfo() {
      return deviceInfoBuilder_ != null || deviceInfo_ != null;
    }
    /**
     * <code>.submit_booking.DeviceInfo device_info = 1;</code>
     */
    public schema.DeviceInfo getDeviceInfo() {
      if (deviceInfoBuilder_ == null) {
        return deviceInfo_ == null ? schema.DeviceInfo.getDefaultInstance() : deviceInfo_;
      } else {
        return deviceInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.submit_booking.DeviceInfo device_info = 1;</code>
     */
    public Builder setDeviceInfo(schema.DeviceInfo value) {
      if (deviceInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deviceInfo_ = value;
        onChanged();
      } else {
        deviceInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.DeviceInfo device_info = 1;</code>
     */
    public Builder setDeviceInfo(
        schema.DeviceInfo.Builder builderForValue) {
      if (deviceInfoBuilder_ == null) {
        deviceInfo_ = builderForValue.build();
        onChanged();
      } else {
        deviceInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.submit_booking.DeviceInfo device_info = 1;</code>
     */
    public Builder mergeDeviceInfo(schema.DeviceInfo value) {
      if (deviceInfoBuilder_ == null) {
        if (deviceInfo_ != null) {
          deviceInfo_ =
            schema.DeviceInfo.newBuilder(deviceInfo_).mergeFrom(value).buildPartial();
        } else {
          deviceInfo_ = value;
        }
        onChanged();
      } else {
        deviceInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.DeviceInfo device_info = 1;</code>
     */
    public Builder clearDeviceInfo() {
      if (deviceInfoBuilder_ == null) {
        deviceInfo_ = null;
        onChanged();
      } else {
        deviceInfo_ = null;
        deviceInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.submit_booking.DeviceInfo device_info = 1;</code>
     */
    public schema.DeviceInfo.Builder getDeviceInfoBuilder() {
      
      onChanged();
      return getDeviceInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.submit_booking.DeviceInfo device_info = 1;</code>
     */
    public schema.DeviceInfoOrBuilder getDeviceInfoOrBuilder() {
      if (deviceInfoBuilder_ != null) {
        return deviceInfoBuilder_.getMessageOrBuilder();
      } else {
        return deviceInfo_ == null ?
            schema.DeviceInfo.getDefaultInstance() : deviceInfo_;
      }
    }
    /**
     * <code>.submit_booking.DeviceInfo device_info = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.DeviceInfo, schema.DeviceInfo.Builder, schema.DeviceInfoOrBuilder> 
        getDeviceInfoFieldBuilder() {
      if (deviceInfoBuilder_ == null) {
        deviceInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            schema.DeviceInfo, schema.DeviceInfo.Builder, schema.DeviceInfoOrBuilder>(
                getDeviceInfo(),
                getParentForChildren(),
                isClean());
        deviceInfo_ = null;
      }
      return deviceInfoBuilder_;
    }

    private schema.Location location_;
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.Location, schema.Location.Builder, schema.LocationOrBuilder> locationBuilder_;
    /**
     * <code>.submit_booking.Location location = 2;</code>
     */
    public boolean hasLocation() {
      return locationBuilder_ != null || location_ != null;
    }
    /**
     * <code>.submit_booking.Location location = 2;</code>
     */
    public schema.Location getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? schema.Location.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <code>.submit_booking.Location location = 2;</code>
     */
    public Builder setLocation(schema.Location value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.Location location = 2;</code>
     */
    public Builder setLocation(
        schema.Location.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.submit_booking.Location location = 2;</code>
     */
    public Builder mergeLocation(schema.Location value) {
      if (locationBuilder_ == null) {
        if (location_ != null) {
          location_ =
            schema.Location.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.submit_booking.Location location = 2;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        location_ = null;
        locationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.submit_booking.Location location = 2;</code>
     */
    public schema.Location.Builder getLocationBuilder() {
      
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.submit_booking.Location location = 2;</code>
     */
    public schema.LocationOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            schema.Location.getDefaultInstance() : location_;
      }
    }
    /**
     * <code>.submit_booking.Location location = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        schema.Location, schema.Location.Builder, schema.LocationOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            schema.Location, schema.Location.Builder, schema.LocationOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }

    private java.lang.Object market_ = "";
    /**
     * <pre>
     * e.g.UK,pattern value="^[A-Z]{2}$"
     * </pre>
     *
     * <code>string market = 3;</code>
     */
    public java.lang.String getMarket() {
      java.lang.Object ref = market_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        market_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g.UK,pattern value="^[A-Z]{2}$"
     * </pre>
     *
     * <code>string market = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMarketBytes() {
      java.lang.Object ref = market_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        market_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g.UK,pattern value="^[A-Z]{2}$"
     * </pre>
     *
     * <code>string market = 3;</code>
     */
    public Builder setMarket(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      market_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g.UK,pattern value="^[A-Z]{2}$"
     * </pre>
     *
     * <code>string market = 3;</code>
     */
    public Builder clearMarket() {
      
      market_ = getDefaultInstance().getMarket();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g.UK,pattern value="^[A-Z]{2}$"
     * </pre>
     *
     * <code>string market = 3;</code>
     */
    public Builder setMarketBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      market_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:submit_booking.PointOfSale)
  }

  // @@protoc_insertion_point(class_scope:submit_booking.PointOfSale)
  private static final schema.PointOfSale DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new schema.PointOfSale();
  }

  public static schema.PointOfSale getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PointOfSale>
      PARSER = new com.google.protobuf.AbstractParser<PointOfSale>() {
    @java.lang.Override
    public PointOfSale parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PointOfSale(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PointOfSale> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PointOfSale> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public schema.PointOfSale getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

