// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

public interface PriceBreakdownOrBuilder extends
    // @@protoc_insertion_point(interface_extends:submit_booking.PriceBreakdown)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Surcharge for a specific card type(visa, master, etc).
   * Where the surcharge is a percentage value of the total amount, values can range from (0.01 to 100).
   * The value cannot be 0.
   * </pre>
   *
   * <code>.submit_booking.CardSurcharge card_surcharge = 1;</code>
   */
  boolean hasCardSurcharge();
  /**
   * <pre>
   * Surcharge for a specific card type(visa, master, etc).
   * Where the surcharge is a percentage value of the total amount, values can range from (0.01 to 100).
   * The value cannot be 0.
   * </pre>
   *
   * <code>.submit_booking.CardSurcharge card_surcharge = 1;</code>
   */
  schema.CardSurcharge getCardSurcharge();
  /**
   * <pre>
   * Surcharge for a specific card type(visa, master, etc).
   * Where the surcharge is a percentage value of the total amount, values can range from (0.01 to 100).
   * The value cannot be 0.
   * </pre>
   *
   * <code>.submit_booking.CardSurcharge card_surcharge = 1;</code>
   */
  schema.CardSurchargeOrBuilder getCardSurchargeOrBuilder();

  /**
   * <code>repeated .submit_booking.PricedItem priced_items = 2;</code>
   */
  java.util.List<schema.PricedItem> 
      getPricedItemsList();
  /**
   * <code>repeated .submit_booking.PricedItem priced_items = 2;</code>
   */
  schema.PricedItem getPricedItems(int index);
  /**
   * <code>repeated .submit_booking.PricedItem priced_items = 2;</code>
   */
  int getPricedItemsCount();
  /**
   * <code>repeated .submit_booking.PricedItem priced_items = 2;</code>
   */
  java.util.List<? extends schema.PricedItemOrBuilder> 
      getPricedItemsOrBuilderList();
  /**
   * <code>repeated .submit_booking.PricedItem priced_items = 2;</code>
   */
  schema.PricedItemOrBuilder getPricedItemsOrBuilder(
      int index);
}
