// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

public interface PriceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:submit_booking.Price)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.submit_booking.Amount amount = 1;</code>
   */
  boolean hasAmount();
  /**
   * <code>.submit_booking.Amount amount = 1;</code>
   */
  schema.Amount getAmount();
  /**
   * <code>.submit_booking.Amount amount = 1;</code>
   */
  schema.AmountOrBuilder getAmountOrBuilder();

  /**
   * <code>string currency = 2;</code>
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 2;</code>
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();
}
