// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

public interface SubmitBookingRQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:submit_booking.SubmitBookingRQ)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.submit_booking.AdditionalInfos additional_infos = 1;</code>
   */
  boolean hasAdditionalInfos();
  /**
   * <code>.submit_booking.AdditionalInfos additional_infos = 1;</code>
   */
  schema.AdditionalInfos getAdditionalInfos();
  /**
   * <code>.submit_booking.AdditionalInfos additional_infos = 1;</code>
   */
  schema.AdditionalInfosOrBuilder getAdditionalInfosOrBuilder();

  /**
   * <code>.submit_booking.BasicInfo basic_info = 2;</code>
   */
  boolean hasBasicInfo();
  /**
   * <code>.submit_booking.BasicInfo basic_info = 2;</code>
   */
  schema.BasicInfo getBasicInfo();
  /**
   * <code>.submit_booking.BasicInfo basic_info = 2;</code>
   */
  schema.BasicInfoOrBuilder getBasicInfoOrBuilder();

  /**
   * <code>.submit_booking.ContactInfo contact_info = 3;</code>
   */
  boolean hasContactInfo();
  /**
   * <code>.submit_booking.ContactInfo contact_info = 3;</code>
   */
  schema.ContactInfo getContactInfo();
  /**
   * <code>.submit_booking.ContactInfo contact_info = 3;</code>
   */
  schema.ContactInfoOrBuilder getContactInfoOrBuilder();

  /**
   * <pre>
   * Legs/Segments information
   * </pre>
   *
   * <code>.submit_booking.FlightData flight_data = 4;</code>
   */
  boolean hasFlightData();
  /**
   * <pre>
   * Legs/Segments information
   * </pre>
   *
   * <code>.submit_booking.FlightData flight_data = 4;</code>
   */
  schema.FlightData getFlightData();
  /**
   * <pre>
   * Legs/Segments information
   * </pre>
   *
   * <code>.submit_booking.FlightData flight_data = 4;</code>
   */
  schema.FlightDataOrBuilder getFlightDataOrBuilder();

  /**
   * <pre>
   * Information related to the settlement of a transaction through monetary or other compensations.
   * </pre>
   *
   * <code>.submit_booking.PaymentInfo payment_info = 5;</code>
   */
  boolean hasPaymentInfo();
  /**
   * <pre>
   * Information related to the settlement of a transaction through monetary or other compensations.
   * </pre>
   *
   * <code>.submit_booking.PaymentInfo payment_info = 5;</code>
   */
  schema.PaymentInfo getPaymentInfo();
  /**
   * <pre>
   * Information related to the settlement of a transaction through monetary or other compensations.
   * </pre>
   *
   * <code>.submit_booking.PaymentInfo payment_info = 5;</code>
   */
  schema.PaymentInfoOrBuilder getPaymentInfoOrBuilder();

  /**
   * <pre>
   * Whether the passenger wants to receive marketing message
   * </pre>
   *
   * <code>bool remarketing_consent = 6;</code>
   */
  boolean getRemarketingConsent();

  /**
   * <pre>
   * Offer selected by the Passenger for requesting an Order to be created,
   * which could reference (via the offer_id) from a shopping response.
   * </pre>
   *
   * <code>.submit_booking.SelectedOffer selected_offer = 7;</code>
   */
  boolean hasSelectedOffer();
  /**
   * <pre>
   * Offer selected by the Passenger for requesting an Order to be created,
   * which could reference (via the offer_id) from a shopping response.
   * </pre>
   *
   * <code>.submit_booking.SelectedOffer selected_offer = 7;</code>
   */
  schema.SelectedOffer getSelectedOffer();
  /**
   * <pre>
   * Offer selected by the Passenger for requesting an Order to be created,
   * which could reference (via the offer_id) from a shopping response.
   * </pre>
   *
   * <code>.submit_booking.SelectedOffer selected_offer = 7;</code>
   */
  schema.SelectedOfferOrBuilder getSelectedOfferOrBuilder();

  /**
   * <pre>
   * Items no included in flight base offer but passenger can pay extra money to buy. e.g. Seat, Baggage, Insurance
   * </pre>
   *
   * <code>repeated .submit_booking.OptionalExtra selected_optional_extras = 8;</code>
   */
  java.util.List<schema.OptionalExtra> 
      getSelectedOptionalExtrasList();
  /**
   * <pre>
   * Items no included in flight base offer but passenger can pay extra money to buy. e.g. Seat, Baggage, Insurance
   * </pre>
   *
   * <code>repeated .submit_booking.OptionalExtra selected_optional_extras = 8;</code>
   */
  schema.OptionalExtra getSelectedOptionalExtras(int index);
  /**
   * <pre>
   * Items no included in flight base offer but passenger can pay extra money to buy. e.g. Seat, Baggage, Insurance
   * </pre>
   *
   * <code>repeated .submit_booking.OptionalExtra selected_optional_extras = 8;</code>
   */
  int getSelectedOptionalExtrasCount();
  /**
   * <pre>
   * Items no included in flight base offer but passenger can pay extra money to buy. e.g. Seat, Baggage, Insurance
   * </pre>
   *
   * <code>repeated .submit_booking.OptionalExtra selected_optional_extras = 8;</code>
   */
  java.util.List<? extends schema.OptionalExtraOrBuilder> 
      getSelectedOptionalExtrasOrBuilderList();
  /**
   * <pre>
   * Items no included in flight base offer but passenger can pay extra money to buy. e.g. Seat, Baggage, Insurance
   * </pre>
   *
   * <code>repeated .submit_booking.OptionalExtra selected_optional_extras = 8;</code>
   */
  schema.OptionalExtraOrBuilder getSelectedOptionalExtrasOrBuilder(
      int index);

  /**
   * <pre>
   * Skyscanner booking reference Identifier.
   * </pre>
   *
   * <code>string skyscanner_booking_id = 9;</code>
   */
  java.lang.String getSkyscannerBookingId();
  /**
   * <pre>
   * Skyscanner booking reference Identifier.
   * </pre>
   *
   * <code>string skyscanner_booking_id = 9;</code>
   */
  com.google.protobuf.ByteString
      getSkyscannerBookingIdBytes();

  /**
   * <pre>
   * key = traveler's id
   * </pre>
   *
   * <code>map&lt;string, .submit_booking.TravelerInfo&gt; travelers = 10;</code>
   */
  int getTravelersCount();
  /**
   * <pre>
   * key = traveler's id
   * </pre>
   *
   * <code>map&lt;string, .submit_booking.TravelerInfo&gt; travelers = 10;</code>
   */
  boolean containsTravelers(
      java.lang.String key);
  /**
   * Use {@link #getTravelersMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, schema.TravelerInfo>
  getTravelers();
  /**
   * <pre>
   * key = traveler's id
   * </pre>
   *
   * <code>map&lt;string, .submit_booking.TravelerInfo&gt; travelers = 10;</code>
   */
  java.util.Map<java.lang.String, schema.TravelerInfo>
  getTravelersMap();
  /**
   * <pre>
   * key = traveler's id
   * </pre>
   *
   * <code>map&lt;string, .submit_booking.TravelerInfo&gt; travelers = 10;</code>
   */

  schema.TravelerInfo getTravelersOrDefault(
      java.lang.String key,
      schema.TravelerInfo defaultValue);
  /**
   * <pre>
   * key = traveler's id
   * </pre>
   *
   * <code>map&lt;string, .submit_booking.TravelerInfo&gt; travelers = 10;</code>
   */

  schema.TravelerInfo getTravelersOrThrow(
      java.lang.String key);
}
