// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

public interface TaxOrBuilder extends
    // @@protoc_insertion_point(interface_extends:submit_booking.Tax)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Tax amount. Example: 15000 USD
   * </pre>
   *
   * <code>.submit_booking.Amount amount = 1;</code>
   */
  boolean hasAmount();
  /**
   * <pre>
   * Tax amount. Example: 15000 USD
   * </pre>
   *
   * <code>.submit_booking.Amount amount = 1;</code>
   */
  schema.Amount getAmount();
  /**
   * <pre>
   * Tax amount. Example: 15000 USD
   * </pre>
   *
   * <code>.submit_booking.Amount amount = 1;</code>
   */
  schema.AmountOrBuilder getAmountOrBuilder();

  /**
   * <code>string currency = 2;</code>
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 2;</code>
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <pre>
   * Tax short description. Example: $4 per flight segment, per passenger (U.S. domestic segment tax)
   * </pre>
   *
   * <code>.submit_booking.Description description = 3;</code>
   */
  boolean hasDescription();
  /**
   * <pre>
   * Tax short description. Example: $4 per flight segment, per passenger (U.S. domestic segment tax)
   * </pre>
   *
   * <code>.submit_booking.Description description = 3;</code>
   */
  schema.Description getDescription();
  /**
   * <pre>
   * Tax short description. Example: $4 per flight segment, per passenger (U.S. domestic segment tax)
   * </pre>
   *
   * <code>.submit_booking.Description description = 3;</code>
   */
  schema.DescriptionOrBuilder getDescriptionOrBuilder();

  /**
   * <pre>
   * IATA TTBS Tax Code. Example: AY, GB
   * </pre>
   *
   * <code>string tax_code = 4;</code>
   */
  java.lang.String getTaxCode();
  /**
   * <pre>
   * IATA TTBS Tax Code. Example: AY, GB
   * </pre>
   *
   * <code>string tax_code = 4;</code>
   */
  com.google.protobuf.ByteString
      getTaxCodeBytes();

  /**
   * <pre>
   * The name given to describe the tax. For example, this name can be taken from the IATA TTBS
   * </pre>
   *
   * <code>string tax_name = 5;</code>
   */
  java.lang.String getTaxName();
  /**
   * <pre>
   * The name given to describe the tax. For example, this name can be taken from the IATA TTBS
   * </pre>
   *
   * <code>string tax_name = 5;</code>
   */
  com.google.protobuf.ByteString
      getTaxNameBytes();
}
