// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: submit_booking.proto

package schema;

public interface TravelerInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:submit_booking.TravelerInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();

  /**
   * <code>.submit_booking.Date date_of_birth = 2;</code>
   */
  boolean hasDateOfBirth();
  /**
   * <code>.submit_booking.Date date_of_birth = 2;</code>
   */
  schema.Date getDateOfBirth();
  /**
   * <code>.submit_booking.Date date_of_birth = 2;</code>
   */
  schema.DateOrBuilder getDateOfBirthOrBuilder();

  /**
   * <code>.submit_booking.TravelerInfo.Gender gender = 3;</code>
   */
  int getGenderValue();
  /**
   * <code>.submit_booking.TravelerInfo.Gender gender = 3;</code>
   */
  schema.TravelerInfo.Gender getGender();

  /**
   * <code>.submit_booking.IdentityDoc identity_doc = 4;</code>
   */
  boolean hasIdentityDoc();
  /**
   * <code>.submit_booking.IdentityDoc identity_doc = 4;</code>
   */
  schema.IdentityDoc getIdentityDoc();
  /**
   * <code>.submit_booking.IdentityDoc identity_doc = 4;</code>
   */
  schema.IdentityDocOrBuilder getIdentityDocOrBuilder();

  /**
   * <pre>
   * Is this a lead passenger
   * </pre>
   *
   * <code>bool lead = 5;</code>
   */
  boolean getLead();

  /**
   * <code>.submit_booking.Name name = 6;</code>
   */
  boolean hasName();
  /**
   * <code>.submit_booking.Name name = 6;</code>
   */
  schema.Name getName();
  /**
   * <code>.submit_booking.Name name = 6;</code>
   */
  schema.NameOrBuilder getNameOrBuilder();

  /**
   * <code>.submit_booking.TravelerInfo.TravelerCategoryCode traveler_category_code = 7;</code>
   */
  int getTravelerCategoryCodeValue();
  /**
   * <code>.submit_booking.TravelerInfo.TravelerCategoryCode traveler_category_code = 7;</code>
   */
  schema.TravelerInfo.TravelerCategoryCode getTravelerCategoryCode();

  /**
   * <code>string traveler_id = 8;</code>
   */
  java.lang.String getTravelerId();
  /**
   * <code>string traveler_id = 8;</code>
   */
  com.google.protobuf.ByteString
      getTravelerIdBytes();
}
